"""add_custom_field

Revision ID: 9412a49d1810
Revises: 
Create Date: 2024-05-26 19:46:20.432897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9412a49d1810'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('info_1', sa.String(), nullable=True))
    op.add_column('proxy', sa.Column('info_2', sa.String(), nullable=True))
    op.add_column('proxy', sa.Column('info_3', sa.String(), nullable=True))
    op.add_column('proxy', sa.Column('int_1', sa.Integer(), nullable=True))
    op.add_column('proxy', sa.Column('int_2', sa.Integer(), nullable=True))
    op.add_column('proxy', sa.Column('int_3', sa.Integer(), nullable=True))
    op.add_column('proxy', sa.Column('ts_1', sa.DateTime(), nullable=True))
    op.add_column('proxy', sa.Column('ts_2', sa.DateTime(), nullable=True))
    op.add_column('proxy', sa.Column('ts_3', sa.DateTime(), nullable=True))
    op.add_column('report', sa.Column('info_1', sa.String(), nullable=True))
    op.add_column('report', sa.Column('info_2', sa.String(), nullable=True))
    op.add_column('report', sa.Column('info_3', sa.String(), nullable=True))
    op.add_column('report', sa.Column('int_1', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('int_2', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('int_3', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('ts_1', sa.DateTime(), nullable=True))
    op.add_column('report', sa.Column('ts_2', sa.DateTime(), nullable=True))
    op.add_column('report', sa.Column('ts_3', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'ts_3')
    op.drop_column('report', 'ts_2')
    op.drop_column('report', 'ts_1')
    op.drop_column('report', 'int_3')
    op.drop_column('report', 'int_2')
    op.drop_column('report', 'int_1')
    op.drop_column('report', 'info_3')
    op.drop_column('report', 'info_2')
    op.drop_column('report', 'info_1')
    op.drop_column('proxy', 'ts_3')
    op.drop_column('proxy', 'ts_2')
    op.drop_column('proxy', 'ts_1')
    op.drop_column('proxy', 'int_3')
    op.drop_column('proxy', 'int_2')
    op.drop_column('proxy', 'int_1')
    op.drop_column('proxy', 'info_3')
    op.drop_column('proxy', 'info_2')
    op.drop_column('proxy', 'info_1')
    # ### end Alembic commands ###
